name: Publish on PYPI
on: push

jobs:
  build-n-publish:
    name: Build and publish the package on PYPI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Installing python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Installing `poetry`
        run: python -m pip install poetry

      - name: Build a binary wheel and a source tarball
        run: poetry build

      - name: Publish distribution  to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_UPLOAD_TOKEN }}
          skip_existing: true
          verbose: true
