name: Run tests in tox

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - 3.10.0
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkouting source codes
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions coveralls

    - name: Running the test with `tox`
      run: tox

    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        files: .coverage
        # flags: unittests # optional
        # name: codecov-umbrella # optional
        # fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
